module.exports = function (grunt) {

// -- Config -------------------------------------------------------------------

grunt.initConfig({

    //Convert css to sass, and place in sass directory
    "sass-convert": {

        options: {
          indent: 4
        },

        files: {
            src: [
                'thirdparty/pure/build/*.css',
                '!thirdparty/pure/build/*-min.css',
                '!thirdparty/pure/build/*-context.css',
                '!thirdparty/pure/build/*-core.css',
                '!thirdparty/pure/build/*-nr.css',
                '!thirdparty/pure/build/pure.css'
            ],
            dest: 'sass/pure/_'
        }
    },

    sass_compile_imports: {
        pure_options: {
          options: {
            separator: '',
            importPath: '',
            header: [
                  '// This file is automatically generated to include all pure component files.',
                  '// You can include this in your main index file to include all of pure',
                  '// or pick only the components you need',
                  '',
                  '// WARNING: Do not edit this file directly. Changes may be lost on rebuild',
                  ''
            ]
          },
          target: 'sass/pure/_all.scss',
          src: [
            'sass/pure/*',
            '!sass/pure/_all.scss', 
            '!sass/pure/_grids-responsive-old-ie.scss', 
            '!sass/pure/_grids-units.scss', 
            '!sass/pure/_grids-responsive.scss',
            'sass/pure/_grids-units.scss',
            'sass/pure/_grids-responsive.scss'

          ]
        },
        components_options: {
          options: {
            separator: '',
            importPath: '',
            header: [
                  '// This file is automatically generated to include all files in the component folder.',
                  '// You can include this in your main index file, or pick only the components you need',
                  '',
                  '// To keep this file up-to-date, you can use: grunt watch',
                  '',
                  '// WARNING: Do not edit this file directly. Changes may be lost on rebuild',
                  ''
            ]
          },
          target: 'sass/components/_all.scss',
          src: ['sass/components/*','!sass/components/_all.scss']
        },
        pure_theme_options: {
          options: {
            separator: '',
            importPath: '',
            header: [
                  '// This file is automatically generated to include all files in the pure-theme folder.',
                  '// You can include this in your main index file, or pick only the components you need',
                  '',
                  '// To keep this file up-to-date, you can use: grunt watch',
                  '',
                  '// WARNING: Do not edit this file directly. Changes may be lost on rebuild',
                  ''
            ]
          },
          target: 'sass/pure-theme/_all.scss',
          src: ['sass/pure-theme/*','!sass/pure-theme/_all.scss']
        }
    },
    run_grunt: {
        pure_build: {
            options: {
                log: false,
                task: ['default'],
                process: function(res){
                    if (res.fail){
                        console.log(res);
                    }
                }
            },
            src: ['thirdparty/pure/Gruntfile.js']
        }
    }
});


// Load tasks
grunt.loadNpmTasks('grunt-sass-convert');
grunt.loadNpmTasks('grunt-sass-compile-imports');
grunt.loadNpmTasks('grunt-run-grunt');

grunt.registerTask('index-components', [
    'sass_compile_imports:components_options'
]);

grunt.registerTask('watch', [
    'sass_compile_imports:components_options',
    'sass_compile_imports:pure_theme_options'
]);
grunt.registerTask('default', ['watch']);

// Task to install pure dependencies
grunt.registerTask('npm-install-pure', 'install the backend and frontend dependencies', function() {
    var exec = require('child_process').exec;
    var cb = this.async();
    exec('npm install', {cwd: 'thirdparty/pure'}, function(err, stdout, stderr) {
        console.log(stdout);
        cb();
    });
});

// Build pure
grunt.registerTask('build-pure', [
    'npm-install-pure',
    'run_grunt:pure_build',
    'sass-convert',
    'sass_compile_imports:pure_options'
]);




};
